// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function Click(arg1:number,arg2:number):Promise<void>;

export function DoubleClick(arg1:number,arg2:number):Promise<void>;

export function GoLog(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;
