// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureScreen'](arg1, arg2, arg3, arg4);
}

export function Click(arg1, arg2) {
  return window['go']['main']['App']['Click'](arg1, arg2);
}

export function DoubleClick(arg1, arg2) {
  return window['go']['main']['App']['DoubleClick'](arg1, arg2);
}

export function GoLog(arg1) {
  return window['go']['main']['App']['GoLog'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
